plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - summary.md
  - environment-supported_scenarios-1.md
  - quick_start-1.md
  - quick_start-2.md